### ISSUE TITLE
Implementation of disambiguation as described in 03_vecsigrafo notebook

### ISSUE THREAD

**Issue by kenghweeng** [hybridnlp/tutorial#7]
Hello authors,

First of all, I like your approach to hybridised embeddings and find them really exciting!
I was reading your book and codebase for 03_vecsigrafo Jupyter notebook, and quote:

"We have implemented a lightweight disambiguation strategy, proposed by Mancini, M., Camacho-Collados, J., Iacobacci, I., & Navigli, R. (2017). Embedding Words and Senses Together via Joint Knowledge-Enhanced Training. CoNLL., which has allowed us to produce disambiguated corpora based on WordNet 3.1."

I was wondering curiously if this said implementation could be provided in the scripts folder, thank you :)

**Comment by rdenaux** [comment]
Thanks for reaching out. At the moment, the implementation is an extension of our library for disambiguating with out proprietary technology (Cogito), so it's not that easy to open source (although it doesn't directly rely on Cogito). We'll see if we can extract the implementation as a standalone library, which would be the ideal solution.

Our company is working on a [cloud based API](https://developer.expert.ai/ui) which will allow you to run our proprietary disambiguator. We're working on adapting our tutorial/notebooks so that you will be able to compare the Vecsigrafo (and Transigrafo) disambiguation with the Cogito (rule-based) disambiguation.  We'll probably need a couple of weeks to get this working and tested, but I'll try to remember to add a comment to this issue when we push the changes so you get a notification.
